### ISSUE TITLE
Feature Request: Deleter

### ISSUE THREAD

**Issue by lakai** [NeuroAssassin/Toxic-Cogs#22]
Instead of deleting everything, I would be super useful for it to delete based on word or regex.

**Comment by Predeactor** [comment]
The idea is good, but already exist:
- Filter cog from Core to for words or sentence.
- Trusty's retrigger cog for Regex.

**Comment by NeuroAssassin** [comment]
As @Predeactor said, this is already possible through other core and 3rd party cogs.  Additionally, this cog was a bounty request, and was asked specifically for the way it is currently.  Thank you for giving your time to create this issue, but I'm afraid I have to close it due to the reasons above.  If you have any other suggestions, feel free to create another issue.
